name: Release

on:
  push:
    branches:
      - main
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_APP_PRIVATE_KEY }}
      - uses: GoogleCloudPlatform/release-please-action@main
        with:
          release-type: php
          package-name: insys-symfony-maintenance-bundle
          token: ${{ steps.generate-token.outputs.token }}
